name: build-test-deploy
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check out repository code
              uses: actions/checkout@v4
            - name: use node.js 20.x
              uses: actions/setup-node@v1
              with:
                node-version: '20.x'
            - name: npm install
              run: npm install
            - name: npm run build
              run: npm run build
              
            
